# NOTE: if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"firefox" = "ï‰©"

"kitty" = "ï„ "
"ya" = "ï¼"

"helix" = "ğŸ§¬"
"transmission" = "ï€™"
"music" = "ï€"

"mpv" = "ï€½"
"imv" = "î˜"

[other]
"fallback_icon" = "î­¿"
